DELETE FROM PREMIO_AMMINISTRATIVO;
DELETE FROM PREMIO_ISTRUTTORE;

INSERT INTO PREMIO_AMMINISTRATIVO (IdPremio, Mese, Anno, Punteggio)
VALUES (1, 1, 2026, 50);

INSERT INTO PREMIO_AMMINISTRATIVO (IdPremio, Mese, Anno, Punteggio)
VALUES (2, 4, 2025, 72);

INSERT INTO PREMIO_AMMINISTRATIVO (IdPremio, Mese, Anno, Punteggio)
VALUES (3, 5, 2026, 60);

INSERT INTO PREMIO_AMMINISTRATIVO (IdPremio, Mese, Anno, Punteggio)
VALUES (4, 2, 2026, 54);



INSERT INTO PREMIO_ISTRUTTORE (IdPremio, Mese, Anno, Punteggio)
VALUES (1, 12, 2026, 5);

INSERT INTO PREMIO_ISTRUTTORE (IdPremio, Mese, Anno, Punteggio)
VALUES (2, 3, 2025, 1);

INSERT INTO PREMIO_ISTRUTTORE (IdPremio, Mese, Anno, Punteggio)
VALUES (3, 10, 2026, 2);

INSERT INTO PREMIO_ISTRUTTORE (IdPremio, Mese, Anno, Punteggio)
VALUES (4, 5, 2026, 4);

commit;